#!/usr/bin/env bash
# Write the fish environment that installed toolchains need, into the Dotfiles Repo.
#
# Some Artifacts work fine from PATH but expect an environment variable or a sourced
# include before *other* software can find them. Homebrew reports these as caveats and
# then forgets about them; this turns the ones we care about into a real file:
#
#   .NET SDK   DOTNET_ROOT. The `dotnet` binary itself does not need it — IDEs, language
#              servers and MSBuild-hosted tooling use it to locate the SDK.
#   gcloud     path.fish.inc, which adds the SDK's own bin/ to PATH so components added
#              later with `gcloud components install` are runnable. The core binaries
#              (gcloud, gsutil, bq) are symlinked into the brew prefix and need nothing.
#
# Detection is by *binary on disk*, not by a Homebrew receipt, so this is correct however
# the toolchain arrived and safe to run on a machine that has neither. Anything absent
# contributes nothing to the file; when nothing is installed the file is removed. That
# makes uninstalling a toolchain and re-running this the way to retract its config, and
# it is why the file is generated wholesale rather than appended to.
#
# Output goes to the fish Stow Package in the Dotfiles Repo (so it is version-controlled
# with everything else) and is symlinked live, matching what `stow --no-folding` would
# produce. With no Dotfiles Repo present it writes the real file into ~/.config/fish
# instead, so the script is still useful on a machine that has not been stowed.
#
# fish only: this repo's shell. It writes a conf.d file, which fish auto-loads.
#
# Usage:
#   ./apply-toolchain-env.sh              # detect and apply
#   ./apply-toolchain-env.sh --dry-run    # print what would change, write nothing
#
# Env: TARGET_DOTFILES (default: $HOME/kernvex/dotfiles)
#
# Called at the end of setup.sh; standalone-runnable, and re-running after installing or
# removing a toolchain is the supported way to resync.

set -euo pipefail

TARGET_DOTFILES="${TARGET_DOTFILES:-${HOME}/kernvex/dotfiles}"
DRY_RUN=0

CONF_NAME="esetup-toolchains.fish"
REPO_CONF="${TARGET_DOTFILES}/fish/.config/fish/conf.d/${CONF_NAME}"
LIVE_CONF="${HOME}/.config/fish/conf.d/${CONF_NAME}"

log_info() { echo -e "\033[0;32m[INFO]\033[0m $*"; }
log_warn() { echo -e "\033[0;33m[WARN]\033[0m $*"; }
log_error() { echo -e "\033[0;31m[ERR]\033[0m $*" >&2; }

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) log_error "Unknown flag: $arg (see: $0 --help)"; exit 2 ;;
  esac
done

brew_prefix() { brew --prefix 2>/dev/null || printf '%s' "/opt/homebrew"; }

# The two packagings put the SDK in different places, and DOTNET_ROOT must name the one
# actually installed. Cask first: it is the flavour whose symlink wins in the brew prefix.
detect_dotnet_root() {
  if [[ -x "/usr/local/share/dotnet/dotnet" ]]; then
    printf '%s\n' "/usr/local/share/dotnet"
    return 0
  fi
  local formula_root="$(brew_prefix)/opt/dotnet/libexec"
  if [[ -x "${formula_root}/dotnet" ]]; then
    printf '%s\n' "$formula_root"
    return 0
  fi
  return 1
}

detect_gcloud_path_inc() {
  local candidate
  for candidate in "$(brew_prefix)/share/google-cloud-sdk" "${HOME}/google-cloud-sdk"; do
    if [[ -f "${candidate}/path.fish.inc" ]]; then
      printf '%s\n' "${candidate}/path.fish.inc"
      return 0
    fi
  done
  return 1
}

build_content() {
  local dotnet_root="$1" gcloud_inc="$2"
  printf '%s\n' "# Generated by esetup (scripts/apply-toolchain-env.sh). Do not edit by hand:"
  printf '%s\n' "# it is rewritten wholesale. Re-run that script after installing or removing"
  printf '%s\n' "# a toolchain, and commit the result."
  if [[ -n "$dotnet_root" ]]; then
    printf '\n%s\n' "# .NET SDK. \`dotnet\` runs without this; IDEs and language servers use it to"
    printf '%s\n' "# find the SDK."
    printf '%s\n' "set -gx DOTNET_ROOT \"${dotnet_root}\""
  fi
  if [[ -n "$gcloud_inc" ]]; then
    printf '\n%s\n' "# Google Cloud SDK. Puts components installed via \`gcloud components install\`"
    printf '%s\n' "# on PATH; gcloud/gsutil/bq are already linked into the brew prefix. The include"
    printf '%s\n' "# guards against duplicate PATH entries itself."
    printf '%s\n' "if test -f ${gcloud_inc}"
    printf '%s\n' "  source ${gcloud_inc}"
    printf '%s\n' "end"
  fi
}

# Reproduces what `stow --no-folding` would leave behind. Never clobbers a real file it
# did not create -- that is someone's hand-written config, not ours to overwrite.
link_live() {
  local src="$1"
  if [[ -L "$LIVE_CONF" ]]; then
    [[ "$(readlink "$LIVE_CONF")" == "$src" ]] && return 0
    ln -sfn "$src" "$LIVE_CONF"
    log_info "Repointed ${LIVE_CONF} -> ${src}"
    return 0
  fi
  if [[ -e "$LIVE_CONF" ]]; then
    log_warn "${LIVE_CONF} exists and is not a symlink; leaving it alone."
    log_warn "Remove it and re-run, or run the Dotfiles Repo installer."
    return 0
  fi
  mkdir -p "$(dirname "$LIVE_CONF")"
  ln -s "$src" "$LIVE_CONF"
  log_info "Linked ${LIVE_CONF} -> ${src}"
}

remove_generated() {
  local target="$1"
  [[ -e "$target" || -L "$target" ]] || return 0
  if [[ "$DRY_RUN" -eq 1 ]]; then
    log_info "[dry-run] would remove ${target}"
    return 0
  fi
  rm -f "$target"
  log_info "Removed ${target} (toolchain no longer installed)."
}

main() {
  local dotnet_root="" gcloud_inc=""
  dotnet_root="$(detect_dotnet_root || true)"
  gcloud_inc="$(detect_gcloud_path_inc || true)"

  if [[ -n "$dotnet_root" ]]; then
    log_info "Found .NET SDK: ${dotnet_root}"
  else
    log_info "No .NET SDK found; skipping DOTNET_ROOT."
  fi
  if [[ -n "$gcloud_inc" ]]; then
    log_info "Found Google Cloud SDK: ${gcloud_inc}"
  else
    log_info "No Google Cloud SDK found; skipping its PATH include."
  fi

  # Where the file belongs. The Dotfiles Repo is the home when it exists, so the config
  # is version-controlled; otherwise write the live file directly and say so.
  local dest="" linked=0
  if [[ -d "${TARGET_DOTFILES}/.git" ]]; then
    dest="$REPO_CONF"
    linked=1
  else
    log_warn "No Dotfiles Repo at ${TARGET_DOTFILES}; writing ${LIVE_CONF} directly."
    dest="$LIVE_CONF"
  fi

  if [[ -z "$dotnet_root" && -z "$gcloud_inc" ]]; then
    remove_generated "$dest"
    [[ "$linked" -eq 1 ]] && remove_generated "$LIVE_CONF"
    log_info "Nothing to configure."
    return 0
  fi

  local content
  content="$(build_content "$dotnet_root" "$gcloud_inc")"

  if [[ -f "$dest" ]] && [[ "$(cat "$dest")" == "$content" ]]; then
    log_info "${dest} already up to date."
  elif [[ "$DRY_RUN" -eq 1 ]]; then
    log_info "[dry-run] would write ${dest}:"
    printf '%s\n' "$content" | sed 's/^/    /'
  else
    mkdir -p "$(dirname "$dest")"
    printf '%s\n' "$content" > "$dest"
    log_info "Wrote ${dest}"
  fi

  if [[ "$linked" -eq 1 ]]; then
    if [[ "$DRY_RUN" -eq 1 ]]; then
      log_info "[dry-run] would link ${LIVE_CONF} -> ${dest}"
    else
      link_live "$dest"
    fi
  fi

  log_info "Open a new fish shell (or: exec fish) to pick this up."
}

main
